// This file is generated by CMake. Do not edit it manually.
#pragma once
#include <string>
#include <unordered_map>
#include "Resource.hpp"

LOAD_RESOURCE(fonts_Roboto_Regular_ttf);
LOAD_RESOURCE(fonts_Tenacity_Icons_ttf);
LOAD_RESOURCE(fonts_mntsb_ttf);
LOAD_RESOURCE(fonts_nurik_ttf);
LOAD_RESOURCE(skinblinker_txt);

class ResourceLoader {
public:
    static inline std::unordered_map<std::string, Resource> Resources;
    static void loadResources();
};
