# Writes build_info.h with the git commit and branch. Only the values the client
# actually shows (title bar, crash logs) are generated: nothing about the
# build machine, its user or its install paths.

set(BUILD_INFO_PATH "${CMAKE_BINARY_DIR}/build_info.h")
set(TEMP_BUILD_INFO_PATH "${CMAKE_BINARY_DIR}/build_info.tmp.h")

file(WRITE "${TEMP_BUILD_INFO_PATH}" "// This file is generated by CMake. Do not edit it manually.\n\n")
file(APPEND "${TEMP_BUILD_INFO_PATH}" "#pragma once\n\n")

execute_process(
        COMMAND git rev-parse HEAD
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        OUTPUT_VARIABLE DEXKO_BUILD_VERSION
        OUTPUT_STRIP_TRAILING_WHITESPACE
)
if ("${DEXKO_BUILD_VERSION}" STREQUAL "")
    set(DEXKO_BUILD_VERSION "unknown")
endif()
string(SUBSTRING "${DEXKO_BUILD_VERSION}" 0 7 DEXKO_BUILD_VERSION_SHORT)
file(APPEND "${TEMP_BUILD_INFO_PATH}" "#define DEXKO_BUILD_VERSION \"${DEXKO_BUILD_VERSION}\"\n")
file(APPEND "${TEMP_BUILD_INFO_PATH}" "#define DEXKO_BUILD_VERSION_SHORT \"${DEXKO_BUILD_VERSION_SHORT}\"\n")
message(STATUS "Build version: ${DEXKO_BUILD_VERSION}")

execute_process(
        COMMAND git rev-parse --abbrev-ref HEAD
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        OUTPUT_VARIABLE DEXKO_BUILD_BRANCH
        OUTPUT_STRIP_TRAILING_WHITESPACE
)
if ("${DEXKO_BUILD_BRANCH}" STREQUAL "")
    set(DEXKO_BUILD_BRANCH "unknown")
endif()
file(APPEND "${TEMP_BUILD_INFO_PATH}" "#define DEXKO_BUILD_BRANCH \"${DEXKO_BUILD_BRANCH}\"\n")
message(STATUS "Build branch: ${DEXKO_BUILD_BRANCH}")

execute_process(
        COMMAND ${CMAKE_COMMAND} -E compare_files "${TEMP_BUILD_INFO_PATH}" "${BUILD_INFO_PATH}"
        RESULT_VARIABLE FILES_DIFFER
)

if (FILES_DIFFER)
    message(STATUS "Updating build_info.h")
    file(RENAME "${TEMP_BUILD_INFO_PATH}" "${BUILD_INFO_PATH}")
else()
    message(STATUS "No changes to build_info.h")
    file(REMOVE "${TEMP_BUILD_INFO_PATH}")
endif()
